"""The hashed Python dependency locks, checked offline on every test run.

scripts/lock_python_deps.py resolves the requirements*.txt manifests into the
locks under requirements/, and every install -- CI, the packaged Windows
runtime, a developer setup, a launcher's fix hint -- reads those locks with
``pip install --require-hashes``. CI's "Python dependency locks" job proves each
lock is exactly what its manifest resolves to, but it needs the network and the
pinned compiler. Nothing here does, so these run everywhere and catch the usual
ways the arrangement decays before anything is pushed:

* a manifest edited without regenerating -- a direct dependency added,
  removed, or moved outside the range it now declares;
* a lock entry that is not an exact pin, or carries no hash, which
  --require-hashes refuses outright;
* two locks installed into the same interpreter disagreeing on a version;
* an install path that reads a manifest instead of a lock, or drops
  --require-hashes, and so quietly stops being reproducible.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

import pytest
import yaml
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

from scripts import lock_python_deps as locks

REPO_ROOT = Path(__file__).resolve().parents[1]
HASH = re.compile(r"--hash=sha256:[0-9a-f]{64}")


@dataclass
class Pin:
    version: str
    hashes: list[str]
    via: set[str] = field(default_factory=set)


def parse_lock(path: Path) -> tuple[list[str], dict[str, Pin]]:
    """(header lines, {canonical name: Pin}) for one lock written by uv.

    Every entry is ``name==version [; marker] \\``, then its ``--hash`` lines,
    then a ``# via`` annotation naming what required it: ``-r <manifest>`` for
    a direct dependency, ``-c <lock>`` for a pin a constraint imposed, and the
    names of the packages that depend on it.
    """
    header: list[str] = []
    pins: dict[str, Pin] = {}
    current: Pin | None = None
    in_via = False
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if current is None and line.startswith("#"):
            header.append(line)
        elif line and not line[0].isspace():
            requirement = Requirement(line.rstrip(" \\"))
            specifiers = list(requirement.specifier)
            assert len(specifiers) == 1 and specifiers[0].operator == "==", (
                f"{path.name}: {line!r} is not an exact pin")
            current = Pin(specifiers[0].version, [])
            pins[canonicalize_name(requirement.name)] = current
            in_via = False
        elif stripped.startswith("--hash="):
            assert HASH.fullmatch(stripped.rstrip(" \\")), f"{path.name}: malformed {stripped!r}"
            current.hashes.append(stripped.rstrip(" \\"))
        elif stripped.startswith("# via"):
            source = stripped[len("# via"):].strip()
            if source:
                current.via.add(source)
            in_via = not source
        elif in_via and stripped.startswith("#   "):
            current.via.add(stripped[1:].strip())
        elif stripped:
            pytest.fail(f"{path.name}: unexpected line {line!r}")
    return header, pins


def parse_manifest(path: Path) -> dict[str, Requirement]:
    requirements = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            requirement = Requirement(line)
            requirements[canonicalize_name(requirement.name)] = requirement
    return requirements


def lock_of(layer: locks.Layer) -> dict[str, Pin]:
    return parse_lock(REPO_ROOT / layer.lock)[1]


LAYER_IDS = [layer.name for layer in locks.LAYERS]


# ------------------------------------------------------------ manifest -> lock

@pytest.mark.parametrize("layer", locks.LAYERS, ids=LAYER_IDS)
def test_each_lock_names_the_exact_command_that_produced_it(layer):
    """The header is the lock's provenance: script, compiler, anchor, platform, inputs.

    It is compared with what the script would run TODAY, so a lock generated
    with another anchor, another uv, another platform or other inputs -- or one
    whose script has since changed -- fails here rather than drifting silently.
    """
    header, _pins = parse_lock(REPO_ROOT / layer.lock)
    assert header[:2] == [
        "# This file was autogenerated by uv via the following command:",
        f"#    {locks.header_command(layer)}",
    ]


@pytest.mark.parametrize("layer", locks.LAYERS, ids=LAYER_IDS)
def test_the_locked_direct_dependencies_are_exactly_the_declared_ones(layer):
    """Added, removed or re-ranged in the manifest means regenerated, or this fails."""
    declared = parse_manifest(REPO_ROOT / layer.source)
    pins = lock_of(layer)
    direct = {name for name, pin in pins.items() if f"-r {layer.source}" in pin.via}
    assert direct == set(declared), (
        f"{layer.source} and {layer.lock} disagree on the direct dependencies; "
        "run scripts/lock_python_deps.py")
    for name, requirement in declared.items():
        assert requirement.specifier.contains(pins[name].version, prereleases=True), (
            f"{layer.lock} pins {name}=={pins[name].version}, outside {requirement} "
            f"in {layer.source}")


@pytest.mark.parametrize("layer", locks.LAYERS, ids=LAYER_IDS)
def test_every_pin_is_exact_and_carries_hashes(layer):
    """--require-hashes needs a hash on every entry; without the flag, one
    unhashed entry would switch hash checking off for the whole file."""
    pins = lock_of(layer)
    assert pins, f"{layer.lock} locks nothing"
    unhashed = sorted(name for name, pin in pins.items() if not pin.hashes)
    assert not unhashed, f"{layer.lock} has entries without a hash: {unhashed}"


#: Locks installed into one interpreter: the embedded runtime holds build and
#: runtime; CI holds build and test; a full desktop setup adds optional.
SHARED_INTERPRETERS = [
    (locks.BUILD, locks.RUNTIME), (locks.BUILD, locks.TEST), (locks.RUNTIME, locks.TEST),
    (locks.BUILD, locks.OPTIONAL), (locks.RUNTIME, locks.OPTIONAL),
]


@pytest.mark.parametrize("first,second", SHARED_INTERPRETERS,
                         ids=[f"{a.name}+{b.name}" for a, b in SHARED_INTERPRETERS])
def test_locks_sharing_an_interpreter_agree_on_every_version(first, second):
    """CI must test the versions that ship, and optional must not move the runtime."""
    a, b = lock_of(first), lock_of(second)
    disagreements = sorted((name, a[name].version, b[name].version)
                           for name in set(a) & set(b) if a[name].version != b[name].version)
    assert not disagreements, f"{first.lock} vs {second.lock}: {disagreements}"


def test_ci_tests_the_backend_packages_the_app_ships():
    """Agreement means nothing if the test lock never contained them at all."""
    runtime, test = lock_of(locks.RUNTIME), lock_of(locks.TEST)
    for name in ("eel", "gevent", "bottle", "httpx", "groq", "pydantic", "psutil", "pyyaml"):
        assert name in test, f"{name} ships in {locks.RUNTIME.lock} but CI never installs it"
        assert test[name].version == runtime[name].version


def test_the_compiler_pin_is_the_version_the_script_requires():
    declared = parse_manifest(REPO_ROOT / locks.TOOLS.source)
    assert str(declared["uv"].specifier) == f"=={locks.UV_VERSION}"
    assert lock_of(locks.TOOLS)["uv"].version == locks.UV_VERSION


# ------------------------------------------------ every install reads a lock

def _pip_installs(commands: list[str]) -> list[str]:
    return [command for command in commands if re.search(r"\bpip install\b", command)]


def _assert_locked_install(command: str, where: str) -> str:
    """Return the lock one pip install reads, after checking it is a hashed one."""
    assert "--require-hashes" in command, f"{where}: pip install without --require-hashes: {command}"
    # `-r requirements/x.lock`, PowerShell's `-r (Join-Path $root 'requirements\x.lock')`,
    # or `-c requirements/optional.lock <package>` for a single optional capability.
    match = re.search(r"-[rc]\s+(?:\(Join-Path\s+\$root\s+')?requirements[\\/](\w+)\.lock\b", command)
    assert match, f"{where}: pip install that does not read a lock in requirements/: {command}"
    lock = match.group(1)
    if lock not in {"build", "tools"}:
        # Anything that may hold an sdist installs after build.lock, without
        # build isolation -- see requirements-build.txt.
        assert "--no-build-isolation" in command, (
            f"{where}: {lock}.lock installed with build isolation: {command}")
    return lock


def test_ci_installs_python_packages_only_from_hashed_locks():
    installed: dict[str, list[str]] = {}
    for workflow in sorted((REPO_ROOT / ".github" / "workflows").glob("*.yml")):
        document = yaml.safe_load(workflow.read_text(encoding="utf-8"))
        for job_name, job in document["jobs"].items():
            for step in job.get("steps", []):
                commands = str(step.get("run", "")).splitlines()
                for command in _pip_installs(commands):
                    where = f"{workflow.name}:{job_name}"
                    installed.setdefault(where, []).append(_assert_locked_install(command, where))
    # Not vacuous: the jobs that install Python packages are found, and each
    # installs the build backend before the lock that needs it.
    for where in ("ci.yml:python", "ci.yml:chromium-ui", "build-windows.yml:test"):
        assert installed.get(where) == ["build", "test"], f"{where} installs {installed.get(where)}"
    assert installed.get("ci.yml:dependency-locks") == ["tools"]


def test_ci_regenerates_the_locks_to_detect_drift():
    document = yaml.safe_load((REPO_ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8"))
    runs = [str(step.get("run", "")) for step in document["jobs"]["dependency-locks"]["steps"]]
    assert "python scripts/lock_python_deps.py --check" in runs


def _powershell_commands(source: str) -> list[str]:
    """PowerShell statements with comments removed and backtick continuations joined.

    Comments come out first: this script explains, in prose, exactly the
    install it used to run, and a scan that read comments would match it.
    """
    source = re.sub(r"<#.*?#>", "", source, flags=re.S)
    lines = []
    for line in source.splitlines():
        quote = None
        for index, char in enumerate(line):
            if quote:
                quote = None if char == quote else quote
            elif char in "'\"":
                quote = char
            elif char == "#":
                line = line[:index]
                break
        lines.append(line.rstrip())
    return re.sub(r"`\n\s*", " ", "\n".join(lines)).splitlines()


def test_the_packaged_runtime_installs_only_from_hashed_locks():
    script = REPO_ROOT / "scripts" / "prepare_windows_runtime.ps1"
    commands = _pip_installs(_powershell_commands(script.read_text(encoding="utf-8")))
    installed = [_assert_locked_install(command, script.name) for command in commands]
    assert installed == ["build", "runtime"], f"the embedded runtime installs {installed}"


@pytest.mark.parametrize("launcher,expected", [
    ("NANO.bat", ["build", "runtime"]),
    ("NANO_DESKTOP.bat", ["build", "runtime"]),
    # The speech benchmark measures the voice stack, so it must measure the locked one.
    ("scripts/BENCHMARK_VOZ.bat", ["build", "runtime", "optional"]),
])
def test_launchers_point_a_missing_dependency_at_the_locks(launcher, expected):
    """The fix a launcher prints is the install CI runs, not an unlocked one."""
    lines = [line.strip() for line in (REPO_ROOT / launcher).read_text(encoding="ascii").splitlines()
             if not line.strip().upper().startswith("REM") and not line.strip().startswith("::")]
    installed = [_assert_locked_install(command, launcher) for command in _pip_installs(lines)]
    assert installed == expected, f"{launcher} suggests installing {installed}"
